import { StyleSheet } from "react-native";
import { Colors } from "../../Utils";
import Fonts from "../../Utils/Fonts";

const styles = StyleSheet.create({
  mainContainer: {
    width: "100%",
    height: "100%",
    flexDirection: "column",
  },
  quoteContainer: {
    width: "90%",
    alignSelf: "center",
    marginTop: 20,
  },
  developedTextStyle: {
    textAlign: "center",
    alignSelf: "center",
    fontSize: 16,
    fontFamily: Fonts?.poppinsMedium,
  },
  textContainer: {
    flexDirection: "row",
    alignSelf: "center",
    marginVertical: 20,
  },
  container: {
    borderRadius: 8,
    height: 300,
    alignSelf: "center",
    marginTop: 10,
  },
  header: {
    color: Colors?.WHITE,
    fontSize: 16,
    paddingLeft: 10,
    backgroundColor: Colors?.BLACKTRANSPARENT2,
    borderBottomLeftRadius: 10,
    borderBottomRightRadius: 10,
    fontFamily: Fonts?.poppinsRegular,
  },
  alertHeader: {
    color: Colors?.WHITE,
    fontSize: 15,
    backgroundColor: "red",
    borderTopLeftRadius: 10,
    width: "50%",
    top: 0,
    position: "absolute",
    borderBottomRightRadius: 10,
    fontFamily: Fonts?.poppinsRegular,
    textAlign: "center",
  },
  crossIconStyle: {
    width: 30,
    height: 30,
    borderRadius: 15,
    alignItems: "center",
    justifyContent: "center",
    position: "absolute",
    right: 10,
    top: 10,
  },
  banner: {
    //backgroundColor: Colors?.BLACK,
    position: "absolute",
    width: "100%",
    height: 50,
    bottom: 0,
    alignSelf: "center",
  },
  dateStyle: {
    textAlign: "center",
    fontSize: 14,
    fontFamily: Fonts?.poppinsMedium,
    color: Colors?.BLACKTRANSPARENT,
    width: "90%",
    alignSelf: "center",
  },
  space: {
    height: 100,
    width: "80%",
  },
  headerStyle: {
    fontSize: 16,
    fontFamily: Fonts?.poppinsBold,
    color: Colors?.BLACK,
    width: "90%",
    alignSelf: "center",
    marginTop: 10,
  },
  contentStyle: {
    fontSize: 15,
    fontFamily: Fonts?.poppinsRegular,
    color: Colors?.BLACK,
    width: "90%",
    alignSelf: "center",
    marginBottom: 10,
  },
  notificationsContainer: {
    backgroundColor: Colors?.WHITE,
    width: "90%",
    alignSelf: "center",
    borderRadius: 30,
    borderColor: Colors?.BLACKTRANSPARENT,
    marginVertical: 10,
    paddingVertical: 10,
  },
  imageStyle: {
    width: "95%",
    height: 200,
    alignSelf: "center",
    borderRadius: 15,
  },
  concentRowContainer: {
    width: "100%",
    height: "100%",
  },
  privacyText: {
    paddingLeft: 5,
    fontSize: 14,
    color: Colors?.DARKGREY,
    fontFamily: Fonts?.poppinsRegular,
  },
  privacyTextOne: {
    textDecorationLine: "underline",
    color: Colors?.BLUE,
    fontSize: 14,
    fontFamily: Fonts?.poppinsRegular,
  },
  checkBoxContainer: {
    flexDirection: "row",
    width: "90%",
    alignContent: "center",
    alignItems: "center",
    alignSelf: "center",
    marginTop: 10,
    marginLeft: 20,
  },
  checkBoxStyleOne: {
    width: 22,
    height: 22,
    // backgroundColor: Constant?.COLOR?.BLUEFOUR,
    marginLeft: 25,
    right: 5,
    borderRadius: 4,
    alignItems: "center",
    justifyContent: "center",
    // borderColor: Constant?.COLOR?.BORDERCOLORONE,
    borderWidth: 1,
  },
  modalContainer: {
    width: "95%",
    alignSelf: "center",
    borderRadius: 30,
    paddingVertical: 10,
  },
  modalTitle: {
    fontSize: 20,
    fontFamily: Fonts?.poppinsBold,
    width: "90%",
    alignSelf: "center",
    marginTop: 10,
    textAlign: "center",
  },
  updateFeatureStyle: {
    fontSize: 18,
    fontFamily: Fonts?.poppinsRegular,
    width: "90%",
    alignSelf: "center",
    marginTop: 10,
  },
  closeIconStyle: {
    width: 30,
    height: 30,
    borderRadius: 15,
    alignItems: "center",
    justifyContent: "center",
    position: "absolute",
    right: 20,
    top: 20,
  },
  ratingDesc: {
    fontSize: 18,
    fontFamily: Fonts?.poppinsRegular,
    width: "90%",
    alignSelf: "center",
    marginTop: 10,
    textAlign: "center",
  },
  modalImage: {
    width: 200,
    height: 200,
    alignSelf: "center",
  },
});

export default styles;
